server:
  port: 10010     #网关端口
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848   #nacos地址
      password: nacos
      username: nacos
    sentinel:
      transport:
        dashboard: localhost:8090   #sentinel的地址
    gateway:
      httpclient:
        forward-headers-strategy: native
      server:
        webflux:
          default-filters:
            # 给所有响应添加统一请求头标识
            - AddRequestHeader=origin,gateway
          routes:
            - id: demo1   #路由标识,必须唯一
              uri: lb://demo1   #路由地址，lb代表负载均衡，demo1代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/1/**    #路径断言，代表将路径为1的都转发
            - id: demo2   #路由标识,必须唯一
              uri: lb://demo2   #路由地址，lb代表负载均衡，demo2代表模块服务名。该项可以直接用ip地址代替
              predicates:       #断言，判断是否转发给该路由
                - Path=/2/**    #路径断言，代表将路径为2的都转发
                - After=2026-04-01T00:00:00+08:00